#!/usr/bin/env python

import subprocess as sp
import sys

fn = sys.argv[1]

fh = open(fn + ".tmp.ss", "w")
fh.write("(pretty-print '(" + open(fn).read() + "))")
fh.close()

sp.call("petite --script %s" % (fn + ".tmp.ss"), shell = True)



